### ISSUE TITLE
Pipeline triggering another pipeline is not working

### ISSUE THREAD

**Issue by skim1420** [spinnaker/fiat#114]
Pipeline B is configured to trigger when Pipeline A completes successfully. However, on successful completion of Pipeline A, Pipeline B fails to trigger.

**Comment by leelasharma** [comment]
@ttomsu a similar issue, although the pipeline B is triggered, it fails to run and throws `403 Forbidden`

**Comment by ttomsu** [comment]
cc/ @gardleopard, @ajordens 

spinnaker/orca#1068 linked above will do two things:

1.) Pipelines invoked via the completion of another pipeline (success, failure, whatever) will always that the auth of the person or service account that invoked the parent pipeline. I call this the "implicit flow" because the independent (parent) pipeline doesn't know about the dependent (child) pipeline

2.) Child pipelines invoked via a stage in the parent pipeline will have the auth of the user at the time the stage is ran. For most pipelines, this will be the same user/service account that invoked it (the parent pipeline). However, parent pipelines that have a Manual Judgement stage (MJ) have the option to propagate authentication. In this case, the child pipelines are invoked using the credentials of the human that clicked the "OK to proceed" button.

Do those behaviors make sense and fit your use cases, Gard and Leela?

**Comment by amanya** [comment]
@ttomsu will make perfect sense for us :+1:
