### ISSUE TITLE
Roles passed through SAML assertion are dropped on first sync 

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#41]
Reported by @jvasallo, @ndcampbell

**Comment by ttomsu** [comment]
This issue currently needs to be fixed in Gate, and ported over to Fiat.

**Comment by jvasallo** [comment]
Thanks @ttomsu for this, I was going to mention that I couldn't open up an issue against gate :( 

Here is some more information on our setup (let me know if there is any info I can add to it):

**Ports:**
apiPort: 7777
defaultPort: 8084

**AuthN Methods:**
x509 has been enabled but only used by client scripts/applications to make API Calls to gate
SAML has been enabled for UI access via Deck

**authZ Methods**
We are passing memberOf in the SAML assertion with a list of groups the user is apart of.
We also have configured Github Group Membership for API access

**Experience:**
We have requiredGroupMembership in clouddriver that has both names from Github Groups and names from SAML Assertion. API Access works as expected since it is validating against GitHub groups. When a user logs in via SAML, they are able to browse around and make proper changes based on their groups. After roughly 10 minutes or so (the UserRolesSync period), the user is prompted with a "you have been logged out" message, and they are able to re-auth and hop back on. After looking at the logs, it appeared as though users who have logged in via SAML were being checked against Github group membership only; since they didn't exist they were getting logged out

**Expected:**
Users that login via SAML are able to continue to browse without getting signed out due to their group memberships being checked against Github. In short, SAML users get checked against SAML groups. Github group auth users are checked against github groups.

**Comment by ttomsu** [comment]
Since you have an external roles provider already established, you should just drop the SAML roles from being sent over. The [code](https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesSyncer.groovy#L96) logs a user out if there is a difference in roles between syncs, so if your external provider (GitHub Teams) kept returning the same roles each sync, your users would be able to stay logged in up until the timeout. Would that work for you?

Since these two are independent auth/z features, I'm less inclined to say we should support both simultaneously.

/cc: @jtk54

**Comment by ttomsu** [comment]
Spoke with @jvasallo on Slack. They're setup for users to have SAML roles passed in, but are trying to use X509 certs with email addresses that map to GitHub Teams accounts. The code linked above does in fact work as intended by logging out any user whose roles have changed between syncs. 

As I see it, there are actually two issues here:
1. What to do about the situation above - mixed auth/z in Gate
2. What to do in the future in Fiat - the issue described is definitely present.

A few options considered:
1. For X509 certs, default to including a role with the exact string as the username. Each cert would then be individually whitelisted.
2. Deleting the line of code that logs out a user if their roles change. 
3. Splitting `User.roles` into separate `externalRoles` and `providerRoles` lists.

**Comment by jtk54** [comment]
Isn't the only rub coming from the groups in the initial SAML assertion? If so, the options I see are

* Doing option 3 in Kork
* Doing option 3 in Redis under a different key
* Provide an endpoint that will log out a given user. This should be protected by auth.

Option 2 is insecure, you can have an arbitrarily long session with improper group memberships if the user keeps a browser open.
